apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-deployment
  namespace: jenkins  # Specify the namespace for the deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      serviceAccountName: jenkins-service-account  # Specify the service account
      containers:
      - name: my-java-app
        image: image
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
  namespace: jenkins  # Specify the namespace for the service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: my-java-app
