apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins  # e.g., default or your specific namespace
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
